require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BloomDevelopmentsController do

  # This should return the minimal set of attributes required to create a valid
  # BloomDevelopment. As you add validations to BloomDevelopment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BloomDevelopmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bloom_developments as @bloom_developments" do
      bloom_development = BloomDevelopment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bloom_developments).should eq([bloom_development])
    end
  end

  describe "GET show" do
    it "assigns the requested bloom_development as @bloom_development" do
      bloom_development = BloomDevelopment.create! valid_attributes
      get :show, {:id => bloom_development.to_param}, valid_session
      assigns(:bloom_development).should eq(bloom_development)
    end
  end

  describe "GET new" do
    it "assigns a new bloom_development as @bloom_development" do
      get :new, {}, valid_session
      assigns(:bloom_development).should be_a_new(BloomDevelopment)
    end
  end

  describe "GET edit" do
    it "assigns the requested bloom_development as @bloom_development" do
      bloom_development = BloomDevelopment.create! valid_attributes
      get :edit, {:id => bloom_development.to_param}, valid_session
      assigns(:bloom_development).should eq(bloom_development)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BloomDevelopment" do
        expect {
          post :create, {:bloom_development => valid_attributes}, valid_session
        }.to change(BloomDevelopment, :count).by(1)
      end

      it "assigns a newly created bloom_development as @bloom_development" do
        post :create, {:bloom_development => valid_attributes}, valid_session
        assigns(:bloom_development).should be_a(BloomDevelopment)
        assigns(:bloom_development).should be_persisted
      end

      it "redirects to the created bloom_development" do
        post :create, {:bloom_development => valid_attributes}, valid_session
        response.should redirect_to(BloomDevelopment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bloom_development as @bloom_development" do
        # Trigger the behavior that occurs when invalid params are submitted
        BloomDevelopment.any_instance.stub(:save).and_return(false)
        post :create, {:bloom_development => {  }}, valid_session
        assigns(:bloom_development).should be_a_new(BloomDevelopment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BloomDevelopment.any_instance.stub(:save).and_return(false)
        post :create, {:bloom_development => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bloom_development" do
        bloom_development = BloomDevelopment.create! valid_attributes
        # Assuming there are no other bloom_developments in the database, this
        # specifies that the BloomDevelopment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BloomDevelopment.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => bloom_development.to_param, :bloom_development => { "these" => "params" }}, valid_session
      end

      it "assigns the requested bloom_development as @bloom_development" do
        bloom_development = BloomDevelopment.create! valid_attributes
        put :update, {:id => bloom_development.to_param, :bloom_development => valid_attributes}, valid_session
        assigns(:bloom_development).should eq(bloom_development)
      end

      it "redirects to the bloom_development" do
        bloom_development = BloomDevelopment.create! valid_attributes
        put :update, {:id => bloom_development.to_param, :bloom_development => valid_attributes}, valid_session
        response.should redirect_to(bloom_development)
      end
    end

    describe "with invalid params" do
      it "assigns the bloom_development as @bloom_development" do
        bloom_development = BloomDevelopment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BloomDevelopment.any_instance.stub(:save).and_return(false)
        put :update, {:id => bloom_development.to_param, :bloom_development => {  }}, valid_session
        assigns(:bloom_development).should eq(bloom_development)
      end

      it "re-renders the 'edit' template" do
        bloom_development = BloomDevelopment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BloomDevelopment.any_instance.stub(:save).and_return(false)
        put :update, {:id => bloom_development.to_param, :bloom_development => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bloom_development" do
      bloom_development = BloomDevelopment.create! valid_attributes
      expect {
        delete :destroy, {:id => bloom_development.to_param}, valid_session
      }.to change(BloomDevelopment, :count).by(-1)
    end

    it "redirects to the bloom_developments list" do
      bloom_development = BloomDevelopment.create! valid_attributes
      delete :destroy, {:id => bloom_development.to_param}, valid_session
      response.should redirect_to(bloom_developments_url)
    end
  end

end
