require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BloomsController do

  # This should return the minimal set of attributes required to create a valid
  # Bloom. As you add validations to Bloom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BloomsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all blooms as @blooms" do
      bloom = Bloom.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blooms).should eq([bloom])
    end
  end

  describe "GET show" do
    it "assigns the requested bloom as @bloom" do
      bloom = Bloom.create! valid_attributes
      get :show, {:id => bloom.to_param}, valid_session
      assigns(:bloom).should eq(bloom)
    end
  end

  describe "GET new" do
    it "assigns a new bloom as @bloom" do
      get :new, {}, valid_session
      assigns(:bloom).should be_a_new(Bloom)
    end
  end

  describe "GET edit" do
    it "assigns the requested bloom as @bloom" do
      bloom = Bloom.create! valid_attributes
      get :edit, {:id => bloom.to_param}, valid_session
      assigns(:bloom).should eq(bloom)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bloom" do
        expect {
          post :create, {:bloom => valid_attributes}, valid_session
        }.to change(Bloom, :count).by(1)
      end

      it "assigns a newly created bloom as @bloom" do
        post :create, {:bloom => valid_attributes}, valid_session
        assigns(:bloom).should be_a(Bloom)
        assigns(:bloom).should be_persisted
      end

      it "redirects to the created bloom" do
        post :create, {:bloom => valid_attributes}, valid_session
        response.should redirect_to(Bloom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bloom as @bloom" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bloom.any_instance.stub(:save).and_return(false)
        post :create, {:bloom => {  }}, valid_session
        assigns(:bloom).should be_a_new(Bloom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bloom.any_instance.stub(:save).and_return(false)
        post :create, {:bloom => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bloom" do
        bloom = Bloom.create! valid_attributes
        # Assuming there are no other blooms in the database, this
        # specifies that the Bloom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bloom.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => bloom.to_param, :bloom => { "these" => "params" }}, valid_session
      end

      it "assigns the requested bloom as @bloom" do
        bloom = Bloom.create! valid_attributes
        put :update, {:id => bloom.to_param, :bloom => valid_attributes}, valid_session
        assigns(:bloom).should eq(bloom)
      end

      it "redirects to the bloom" do
        bloom = Bloom.create! valid_attributes
        put :update, {:id => bloom.to_param, :bloom => valid_attributes}, valid_session
        response.should redirect_to(bloom)
      end
    end

    describe "with invalid params" do
      it "assigns the bloom as @bloom" do
        bloom = Bloom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bloom.any_instance.stub(:save).and_return(false)
        put :update, {:id => bloom.to_param, :bloom => {  }}, valid_session
        assigns(:bloom).should eq(bloom)
      end

      it "re-renders the 'edit' template" do
        bloom = Bloom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bloom.any_instance.stub(:save).and_return(false)
        put :update, {:id => bloom.to_param, :bloom => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bloom" do
      bloom = Bloom.create! valid_attributes
      expect {
        delete :destroy, {:id => bloom.to_param}, valid_session
      }.to change(Bloom, :count).by(-1)
    end

    it "redirects to the blooms list" do
      bloom = Bloom.create! valid_attributes
      delete :destroy, {:id => bloom.to_param}, valid_session
      response.should redirect_to(blooms_url)
    end
  end

end
